name: Lint
on: [push, pull_request]
defaults:
  run:
    working-directory: ./admin
jobs:
  lint-admin:
    runs-on: ubuntu-latest
    name: Admin (Next.js)
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: yarn install
      - run: yarn run lint